### ISSUE TITLE
分页问题

### ISSUE THREAD

**Issue by csxuyang** [beihaifeiwu/dolphin#10]
分页在mapper.xml生成好，如果切换数据库的话，需要完全改配置了

**Comment by beihaifeiwu** [comment]
因为xmbg的分页是使用数据库的物理分页而不是基于JDBC的游标，在这一点上和Hibernate之类的工具是没办法相比的

**Comment by csxuyang** [comment]
我看别人有用拦截器去做分页，但在mbg中没有想好怎么去做
