### ISSUE TITLE
生成mapper是不是有问题呢？ 好多传实体的方法传的是null

### ISSUE THREAD

**Issue by csxuyang** [beihaifeiwu/dolphin#3]
int batchInsert(List<null> list);

```
int batchUpdate(List<null> list);

int upsert(@Param("record") LoginUser record, @Param("array") String[] array);

int batchUpsert(@Param("records") List<null> list, @Param("array") String[] array);
```

**Comment by beihaifeiwu** [comment]
首先感谢你提出这个issue，这个版本的xmbg还用很多不成熟的地方，由于工作调度的原因开发进度被耽误了，最近恢复开发，不久就会放出新的版本，你提出的问题我会尽量在新版本中修复的

**Comment by beihaifeiwu** [comment]
我在开发新版本过程中对这个BUG进行了测试，但是并未能复现你这个问题：

```
    int batchInsert(List<User> list);
    int batchUpdate(List<User> list);
```

可能在开发测试用例的过程中修复掉了

**Comment by lytofb** [comment]
你好，现版本还是有这个问题存在，我发现是因为在generateConfig.xml的table节点中，使用了tableName=%来匹配数据库表，会出现生成Mapper中有Null的情况，可以修改对应clientGenerated方法中的参数，将33行中FullyQuailifiedJavaType的参数改为
"java.util.List<" + CaseFormat.UPPER_UNDERSCORE.to(CaseFormat.UPPER_CAMEL, introspectedTable.getFullyQualifiedTableNameAtRuntime()) + ">"
即可
