### ISSUE TITLE
Mapper 里报一个错找不到 BaseResultMap

### ISSUE THREAD

**Issue by csxuyang** [beihaifeiwu/dolphin#5]
去掉就可以正常了，是不是不是必须的，因为找不到在Mapper.xml里定义的BaseResultMap

**Comment by beihaifeiwu** [comment]
xmbg只在公司的项目中用过，可能有些地方没考虑到，最近正在完善测试用例

**Comment by beihaifeiwu** [comment]
该问题已在1.0.0版本中解决，很快就会放出
