### ISSUE TITLE
能否增加个demo

### ISSUE THREAD

**Issue by csxuyang** [beihaifeiwu/dolphin#8]
比较喜欢这个插件，能否增加个demo，方便查看，因为在使用过程中会很多问题，但是不太好查找

谢谢

**Comment by beihaifeiwu** [comment]
新的版本放出后会给出一个完整的demo的

**Comment by csxuyang** [comment]
现在我想请问一下从controller调用dao的selectByExample 方法的参数如何组织(暂时先不考虑service层的问题)，我不想手工去做userInfoExample.createCriteria().andUserIdEqualTo(); 类似上面说的代码，这样代码太无效了，大部分代码都需要手工去写

**Comment by beihaifeiwu** [comment]
一般这种情况下，传递的参数都是和你的业务逻辑相关的，业务逻辑千变万化，没有一个固定的形式，而表述这种业务的方式有两种 1. 配置（包括约定）  2.硬编码， 所以才会有系统复杂性

**Comment by csxuyang** [comment]
针对于配置能否给予些提示?谢谢

**Comment by beihaifeiwu** [comment]
简单一点可以是xml的方式例如

```
 <invoke name="login" value="somm.class.method">
       <param order='1' value='${expression for first param}'/>
       <param order='2' value='${expression for second param}'/>
 </invoke>
```

不过这种方式和硬编码比并没有太大优势

**Comment by csxuyang** [comment]
嗯，这种也不是我想要的
